<?php

define('ALUMNI_CAS_AUTH_EXCLUDE', 'services/*');

/**
 * Implements hook_menu().
 */
function alumni_cas_auth_menu() {
  global $user;
  $items = array();
  $items['admin/config/people/alumni-cas-auth'] = array(
    'title' => 'Alumni Cas Auth settings',
    'description' => 'Configure Alumni Cas Auth settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alumni_cas_auth_admin_settings'),
    'access arguments' => array('administer alumni cas auth'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'alumni_cas_auth.admin.inc',
  );
  /*
  $items['alumni-cas-login'] = array(
    'path' => 'alumni-cas-login',
    'title' => 'Alumni Cas Login',
    'page callback' => 'alumni_cas_auth_login_page',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_SUGGESTED_ITEM,
  );
  $items['alumni-cas-logout'] = array(
    'title' => 'Alumni Cas Logout',
    'page callback' => 'alumni_cas_auth_logout',
    'access callback' => 'alumni_cas_auth_user_is_logged_in',
    'type' => MENU_SUGGESTED_ITEM,
  );
  */
  return $items;
}

/**
 * Implements hook_permission().
 */
function alumni_cas_auth_permission() {
  return array(
    'administer alumni cas auth' => array(
      'title' => t('Administer Cas Auth settings'),
      'description' => t('Configure redirection, login/logout redirection, and other settings.'),
      'restrict access' => TRUE,
    ),
    'download alumni cas private files' => array(
      'title' => t('Download Alumni Cas Private Files'),
      'description' => t('Allow access to Alumni Cas Private Files.'),
      'restrict access' => TRUE,
    )
  );
}

/**
 * Implementation of hook_init
 * Redirect to cas if not authenicated
 * Log in user if cas authenicated successfull
 */
function alumni_cas_auth_init() {
  global $user;
  if (!_alumni_cas_auth_force_login()) {
    return;
  }
  if (user_is_logged_in()) {
    // user is logged in, nothing more to do
    return;
  }
  $alumni_cas_user = alumni_cas_auth_user_init();
  // check if we are returning from a cas login
  if ($alumni_cas_user->returning_from_cas_login()) {
    // check authenication response from cas
    if (!$alumni_cas_user->is_authenicated()) {
      // authenicate the cas user
      $alumni_cas_user->authenicate();
    }
    $user = alumni_cas_auth_load_user($alumni_cas_user);
    if ($user->uid) {
      user_login_finalize();
    }
  } else {
    // authenicate the cas user
    $alumni_cas_user->authenicate();
  }
}

/**
 * Initialize AlumniCasUser.
 *
 * Will load a AlumniCasUser object.
 */
function alumni_cas_auth_user_init() {
  // Load AlumniCasUser
  module_load_include('inc', 'alumni_cas_auth', 'alumni_cas_user');
  return new AlumniCasUser();
}

function alumni_cas_auth_load_user($alumni_cas_user) {
  watchdog(WATCHDOG_INFO, 'alumni_cas_auth_load_user');
  $user_id = $alumni_cas_user->get_user_id();
  $data_url = cas_get_data_url($user_id);
  watchdog(WATCHDOG_INFO, 'alumni_cas_auth_load_user data_url = ' . $data_url);
  $user_name = _alumni_cas_auth_get_user_name($data_url);
  $user_name = str_replace('OK:', '', $user_name);
  $user_name = trim($user_name);
  watchdog(WATCHDOG_INFO, 'alumni_cas_auth_load_user user_name = ' . $user_name);
  $name = 'cas-' . $alumni_cas_user->get_stanford_id();
  $found_user = user_load_by_name($name);
  if ($found_user) {
    return $found_user;
  }
  $alumnipg_role = user_role_load_by_name('alumnipg');
  $new_user = user_save('', array(
    'name' => $user_name . ' ' . substr($user_id,-4),
    'pass' => '',
    'mail' => $user_name . '@alumni.example.com',
    'init' => $user_name,
    'status' => 1,
    'roles' => array($alumnipg_role->rid => $alumnipg_role->rid)
  ));
  watchdog(WATCHDOG_INFO, 'alumni_cas_auth_load_user new user = ' . $user_name . ' ' . substr($user_id,-4));
  return $new_user;
}

function _alumni_cas_auth_get_user_name($url) {
  $return = drupal_http_request($url);
  if ($return->code == 200) {
    return $return->data;
  }
  return '';
}

/**
 * Determine if we should require the user be authenticated.
 *
 * @return
 *   TRUE if we should require the user be authenticated, FALSE otherwise.
 */
function _alumni_cas_auth_force_login() {
  // The 'alumni_cas_auth' page is a shortcut to force authentication.
  if (arg(0) == 'alumni-cas-login') {
    return TRUE;
  }

  // Do not force login for XMLRPC, Cron, or Drush.
  if (stristr($_SERVER['SCRIPT_FILENAME'], 'xmlrpc.php')) {
    return FALSE;
  }
  if (stristr($_SERVER['SCRIPT_FILENAME'], 'cron.php')) {
    return FALSE;
  }
  if (function_exists('drush_verify_cli') && drush_verify_cli()) {
    return FALSE;
  }

  // Excluded page do not need login.
  if ($pages = variable_get('alumni_cas_auth_exclude', ALUMNI_CAS_AUTH_EXCLUDE)) {
    $path = drupal_get_path_alias($_GET['q']);
    if (drupal_match_path($path, $pages)) {
      return FALSE;
    }
  }

  // Set the default behavior.
  $force_login = variable_get('alumni_cas_auth_access', 0);

  // If we match the specified paths, reverse the behavior.
  if ($pages = variable_get('alumni_cas_auth_pages', '')) {
    $path = drupal_get_path_alias($_GET['q']);
    if (drupal_match_path($path, $pages)) {
      $force_login = !$force_login;
    }
  }

  // If we match the private files path, force login
  if ($private_files_path = variable_get('alumni_cas_auth_private_files', '')) {
    $path = drupal_get_path_alias($_GET['q']);
    $private_files_path = 'system/files/' . $private_files_path;
    if (drupal_match_path($path, $private_files_path)) {
      $force_login = 1;
    }
  }

  return $force_login;
}

function alumni_cas_auth_file_download($uri, $field_type = 'file') {
  if (variable_get('alumni_cas_auth_check_private_file_access', 1) && drupal_match_path($uri,'private://' . variable_get('alumni_cas_auth_private_files_base_path', ''))) {
    if (!user_access('download alumni cas private files')) {
      return -1;
    }
  }
  return null;
}
