<?php

define('ALUMNI_CAS_AUTH_EXCLUDE', 'services/*');

/**
 * Implements hook_menu().
 */
function alumni_cas_auth_menu() {
  global $user;
  $items = array();
  $items['admin/config/people/alumni-cas-auth'] = array(
    'title' => 'Alumni Cas Auth settings',
    'description' => 'Configure Alumni Cas Auth settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alumni_cas_auth_admin_settings'),
    'access arguments' => array('administer alumni cas auth'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'alumni_cas_auth.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function alumni_cas_auth_permission() {
  return array(
    'administer alumni cas auth' => array(
      'title' => t('Administer Cas Auth settings'),
      'description' => t('Configure redirection, login/logout redirection, and other settings.'),
      'restrict access' => TRUE,
    )
  );
}

/**
 * Implementation of hook_init
 * Redirect to cas if not authenicated
 * Log in user if cas authenicated successfull
 */
function alumni_cas_auth_init() {
  global $user;	
  $pos = strpos($_SERVER['REQUEST_URI'], 'programs/mba');
  if ($pos === false) {  
    return;
  }    
  if (user_is_logged_in()) {
    // user is logged in, nothing more to do
    return;
  }
  $alumni_cas_user = alumni_cas_auth_user_init();
  // check if we are returning from a cas login
  if ($alumni_cas_user->returning_from_cas_login()) {
    // check authenication response from cas
    if (!$alumni_cas_user->is_authenicated()) {
      // authenicate the cas user
      $alumni_cas_user->authenicate();
    }
    $user = alumni_cas_auth_load_user($alumni_cas_user);
    if ($user->uid) {
      user_login_finalize();
    }
  } else {
    // authenicate the cas user
    $alumni_cas_user->authenicate();
  }
}

/**
 * Initialize AlumniCasUser.
 *
 * Will load a AlumniCasUser object.
 */
function alumni_cas_auth_user_init() {
  // Load AlumniCasUser
  module_load_include('inc', 'alumni_cas_auth', 'alumni_cas_user');
  return new AlumniCasUser();
}

function alumni_cas_auth_load_user($alumni_cas_user) {
  $data_url = cas_get_data_url($user_id);
  $user_name = _alumni_cas_auth_get_user_name($data_url);
  $name = 'cas-' . $alumni_cas_user->get_stanford_id();
  $found_user = user_load_by_name($name);
  if ($found_user) {
    return $found_user;
  }
  $new_user = user_save('', array(
    'name' => $name,
    'pass' => '',
    'mail' => $name . '@fake.fake',
    'init' => $name,
    'status' => 1,
    'roles' => array())
  );
  return $new_user;
}

function _alumni_cas_auth_get_user_name($url) {
  $return = drupal_http_request($url);
  if ($return->code == 200) {
    return $return->data;
  }
  return '';
}
